### ISSUE TITLE
django 1.7 compatible

### ISSUE THREAD

**Issue by ewiger** [ewiger/picostack#5]
on django 1.7

**sudo picostk init db**

results in

```
Traceback (most recent call last):
  File "/usr/local/bin/picostk", line 429, in <module>
    args.handler(args)
  File "/usr/local/bin/picostk", line 311, in process_init_cmds
    instance.init_db()
  File "/usr/local/bin/picostk", line 197, in init_db
    management.call_command('syncdb', interactive=True, verbosity='1')
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 93, in call_command
    app_name = get_commands()[name]
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 73, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by ewiger** [comment]
somewhat similar error is 
```
 Traceback (most recent call last):
  File "/usr/local/bin/picostk", line 10, in <module>
    execfile(__file__)
  File "/home/pstk/picostack_app/picostk", line 431, in <module>
    args.handler(args)
  File "/home/pstk/picostack_app/picostk", line 254, in run_as_daemon
    daemon_runner.do_action()
  File "/usr/local/lib/python2.7/dist-packages/daemoncxt/runner.py", line 186, in do_action
    func(self)
  File "/usr/local/lib/python2.7/dist-packages/daemoncxt/runner.py", line 131, in _start
    self.app.run()
  File "/home/pstk/picostack_app/picostack/deamon_app.py", line 142, in run
    self.step()
  File "/home/pstk/picostack_app/picostack/deamon_app.py", line 137, in step
    self.vm_manager.destory_machines()
  File "/home/pstk/picostack_app/picostack/vm_manager.py", line 217, in destory_machines
    self.remove_machine(machine)
  File "/home/pstk/picostack_app/picostack/vm_manager.py", line 367, in remove_machine
    machine.delete()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/base.py", line 895, in delete
    collector.collect([self])
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/deletion.py", line 219, in collect
    for related in get_candidate_relations_to_delete(model._meta):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/deletion.py", line 67, in <genexpr>
    f for f in candidate_model_fields
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/deletion.py", line 62, in <genexpr>
    opts.get_fields(include_hidden=True) for opts in candidate_models
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 740, in get_fields
    return self._get_fields(include_parents=include_parents, include_hidden=include_hidden)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 802, in _get_fields
    all_fields = self._relation_tree
  File "/usr/local/lib/python2.7/dist-packages/django/utils/functional.py", line 60, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 709, in _relation_tree
    return self._populate_directed_relation_graph()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/options.py", line 681, in _populate_directed_relation_graph
    all_models = self.apps.get_models(include_auto_created=True)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 168, in get_models
    self.check_models_ready()
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.

```
